### PR TITLE
Revamp file connector and start 4.x.x version

### PR DESCRIPTION
**Pull request by abeykoon**
## Purpose

Revamp the existing file connector to improve usability, make it easy to use. 

## Goals

1. Support all operations the previous connector supported and add more as relevant
2. Rename operations and inputs in a much more meaningful way
3. Test all the file connector operations
4. Bring in the `connection concept` and make it easy to configure FTP,FTPS and SFTP protocols apart from local file system support. 

Also did some research on existing file connectors and related capabilities of competitors and how they have organised the connector operations. 

## Approach

Did a competitor analysis
Come up with a design proposal 
Implement it using VFS library
Test the operations and document it

## Release note

New connector with revamped operations and inputs. 
Added capability to add connections so that users can configure relevant connection to each operation. 
Improved usability configuring FTP, FTPS and SFTP connections.
Utilise File object caching in VFS library for improved performance. 
New property view support in Integration Studio 

## Documentation
Internal doc prepared (EI team folder >> Connectors >> File Connector Documentation)

## Training
N/A

## Certification
N/A

## Marketing
Please find content in release note and documentation 

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples

Can be found in documentation (example page) 

## Migrations (if applicable)
Cannot mirage from 2.x or 3.x file connector versions. Understand and re-configure. 

## Test environment
EI 7.1.0 
JDK 8

### CODE REVIEW

**Comment by abeykoon** [comment]
Code review notes: 

Day1

>> Add a output property for "check exists" file operation so that current body in message context will not get replaced  
>> Add default value for content property in "write" operation  - $body
>> Rename content property to output expression and keep default val as $body in "write" operation
>> Organize read operation parameters as input and output
>> Remove retry count from connection parameters
>> Future- read a file chunk by chunk and feed the result to a sequence for processing (will not be done in this iteration)


Day2

Integration Studio Property panel update : General -- > Connection
Integration Studio improvement - Make text area larger
Try and see to ditect if there is an already registered connection by the same name at the deployment time.  
Define inputs names as local class level constants
Extend exceptions from ConnectException
Change File.Separator to Unix file separator as we use VFS
Review lock file implementation and test
Review Todos that were missed and fix

**Comment by abeykoon** [comment]
@Nirothipan 

As you have pointed out in the review, I created two integration projects with file connector included and created the same connection in each project. As local entries representing connections are local to each project, they got created with no issue. 

However, when I deployed the two CApps from two projects, deployment fails - as it cannot deploy two local entries by the same name. :) So if developers use the same connection name unknowingly in different projects, it is directed at deployment time. Nothing to be done at connector front. So we are safe. 

[2020-11-01 07:59:09,717] ERROR {AbstractSynapseArtifactDeployer} - Deployment of synapse artifact failed. Error reading /Users/hasitha/temp/migration-docs/wso2ei-7.1.0/micro-integrator/tmp/carbonapps/-1234/1604197749631testTwoCompositeExporter_1.0.0.car/myLocalFileConnection_1.0.0/myLocalFileConnection-1.0.0.xml : LocalEntry Deployment from the file : /Users/hasitha/temp/migration-docs/wso2ei-7.1.0/micro-integrator/tmp/carbonapps/-1234/1604197749631testTwoCompositeExporter_1.0.0.car/myLocalFileConnection_1.0.0/myLocalFileConnection-1.0.0.xml : Failed. org.apache.axis2.deployment.DeploymentException: LocalEntry Deployment from the file : /Users/hasitha/temp/migration-docs/wso2ei-7.1.0/micro-integrator/tmp/carbonapps/-1234/1604197749631testTwoCompositeExporter_1.0.0.car/myLocalFileConnection_1.0.0/myLocalFileConnection-1.0.0.xml : Failed.
at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:214)
----
Caused by: org.apache.synapse.SynapseException: Duplicate entry definition for key : myLocalFileConnection
at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1673)
at org.apache.synapse.config.SynapseConfiguration.assertAlreadyExists(SynapseConfiguration.java:2003)
at org.apache.synapse.config.SynapseConfiguration.addEntry(SynapseConfiguration.java:731)
at org.apache.synapse.deployers.LocalEntryDeployer.deploySynapseArtifact(LocalEntryDeployer.java:63)
... 73 more

**Comment by abeykoon** [comment]
As per VFS documentation, upon windows local file system also VFS uses `/` as path separator. 
Thus instead of `File.separator` I will use unix file separator (`/`) across.

**Comment by abeykoon** [comment]
Used strategy pattern to simplify connection setup based on the file protocol. 
Thanks @Asitha for pointing out.

**Review by sajithaliyanage — APPROVED** [review]

**Pull request merged**
